server.port=8081
spring.application.name=vLLM
app.model.url=${LLM_MODEL_URL:http://localhost:8000}
app.model.name=${LLM_MODEL_NAME:Qwen/Qwen2.5-1.5B-Instruct}

# PostgreSQL Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/lmcache
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

